(test
 (name finite_kan_test)
 (modules finite_kan_test)
 (libraries finite_kan))

(test
 (name finite_term_test)
 (modules finite_term_test)
 (libraries finite_term))

(test
 (name finite_substitution_test)
 (modules finite_substitution_test)
 (libraries finite_term))

(test
 (name finite_normalize_test)
 (modules finite_normalize_test)
 (libraries finite_term))

(test
 (name finite_conversion_test)
 (modules finite_conversion_test)
 (libraries finite_term))
